public enum TokenType {
    LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE,

    COMMA,DOT, MINUS, PLUS,SEMICOLON,SLASH,STAR,

    EQUAL, EQUAL_EQUAL,BANG, BANG_EQUAL,
    LESS,LESS_EQUAL,GREATER,GREATER_EQUAL,

    STRING,
    NUMBER,
    IDENTIFIER,
    
    AND, CLASS, ELSE, FALSE, FOR, FUN, IF, NIL, OR, PRINT, RETURN, SUPER, THIS, TRUE, VAR, WHILE,

    UNEXPECTED_CHARACTER_ERROR, UNTERMINATED_STRING_ERROR
}
