public enum TokenType {
    LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE,

    COMMA,DOT, MINUS, PLUS,SEMICOLON,SLASH,STAR,

    EQUAL, EQUAL_EQUAL,BANG, BANG_EQUAL,
    LESS,LESS_EQUAL,GREATER,GREATER_EQUAL,

    STRING,
    NUMBER,

    UNEXPECTED_CHARACTER_ERROR, UNTERMINATED_STRING_ERROR
}
